# cc_library(
#     name = "iw_logging",
#     hdrs = [
#         "include/iw_logging/logger_base.hpp",
#         "include/iw_logging/std_logger.hpp"
#     ],
#     strip_include_prefix = "include/",
#     visibility = ["//visibility:public"],
# )